
const newsletterEmail = async (firstName, lastName, content) => {
  const myvar = `${'<!DOCTYPE html>'
    + '<html lang="en">'
    + '  <head>'
    + '    <meta charset="utf-8" />'
    + '    <title>News Letter</title>'
    + '    <link'
    + '      rel="stylesheet"'
    + '      href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"/>'
    + '    <style type="text/css">'
    + '      body {'
    + '        font-family: Arial, sans-serif !important;'
    + '        color: #222222;'
    + '      }'
    + '      table {'
    + '        width: 100%;'
    + '      }'
    + '    </style>'
    + '  </head>'
    + '<body>'
    + '    <div'
    + '      style="width: 760px; margin: 30px auto;background:linear-gradient(to top,#f6f6f6 75%,#233c7e 25%);padding:20px;"'
    + '    >'
    + '      <table'
    + '        style="width:100%;padding:20px;background:#ffffff;border-bottom:1px solid #233c7e;"'
    + '      >'
    + '        <tr>'
    + '          <td style="text-align: center;">'
    + '            <p style="font-size: 30px; color: #464646;margin-bottom: 0;">'
    + '              Hello <b>'}${firstName}  ${lastName}</b>, `
    + '            </p>'
    + '          </td>'
    + '          </tr>'
    + '        <tr>'
    + '          <td style="text-align: center;">'
    + '            <p style="font-size: 24px; color: #464646;margin-bottom: 0;">'
    + `               ${content}`
    + '            </p>'
    + '          </td>'
    + '          </tr>'
    + '  </table>'
    + ''
    + '      <table style="width:100%;padding:20px;background:#ffffff;">'
    + '        <tr>'
    + '          <td style="text-align: center;">'
    + '            <a'
    + '              href="#"'
    + '              style="width: 30px; height: 30px;display: inline-block;margin: auto 5px;"'
    + '              ><img'
    + '                src="/images/facebook.png"'
    + '                style="width:100%;"'
    + '              />'
    + '            </a>'
    + '            <a'
    + '              href="#"'
    + '              style="width: 30px; height: 30px;display: inline-block;margin: auto 5px;"'
    + '              ><img'
    + '                src="/images/twitter.png"'
    + '                style="width:100%;"'
    + '            /></a>'
    + '          </td>'
    + '        </tr>'
    + '      </table>'
    + '    </div>'
    + '  </body>'
    + '</html>';
  return myvar;
}
module.exports = {
  newsletterEmail
};
